if(WIN32)
    add_compile_definitions(EMBER_PLATFORM_WINDOWS)
    message(STATUS "Ember platform: Windows")
elseif(APPLE)
    add_compile_definitions(EMBER_PLATFORM_MACOS)
    message(STATUS "Ember platform: macOS")
elseif(UNIX)
    add_compile_definitions(EMBER_PLATFORM_LINUX)
    message(STATUS "Ember platform: Linux")
else()
    message(FATAL_ERROR "Unsupported platform")
endif()
